# Mall _Customer Csv

In [1]:
import pandas as pd

In [86]:
df=pd.read_csv('../../datasets/Mall_Customers.csv')
df

CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [26]:
X=df[['Spending Score (1-100)','Age']]
y=df['Annual Income (k$)']

In [27]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X,y)


LinearRegression()

In [28]:
model.coef_
# from sklearn.metrics import mean_absolute_error,mean_squared_error

array([ 0.00665876, -0.01928295])

In [29]:
model.intercept_

60.974873017755804

In [30]:
model.predict([[30,23]])

C:\Users\Hp\DSML39\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([60.73112787])

In [31]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [38]:
mean_absolute_error(y_act,y_pre)

20.988402959038357

In [39]:
mean_squared_error(y_act,y_pre)

686.2546249086264

In [36]:
y_act=y
y_pre=model.predict(X)

# Obestiy Classification

In [10]:
import pandas as pd

In [40]:
df=pd.read_csv('../../datasets/Obesity Classification.csv')
df

ID  Age  Gender  Height  Weight   BMI          Label
0      1   25    Male     175      80  25.3  Normal Weight
1      2   30  Female     160      60  22.5  Normal Weight
2      3   35    Male     180      90  27.3     Overweight
3      4   40  Female     150      50  20.0    Underweight
4      5   45    Male     190     100  31.2          Obese
..   ...  ...     ...     ...     ...   ...            ...
103  106   11    Male     175      10   3.9    Underweight
104  107   16  Female     160      10   3.9    Underweight
105  108   21    Male     180      15   5.6    Underweight
106  109   26  Female     150      15   5.6    Underweight
107  110   31    Male     190      20   8.3    Underweight

[108 rows x 7 columns]

In [41]:
X=df[['Age','Weight']]
y=df['BMI']

In [42]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X,y)

LinearRegression()

In [43]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [44]:
model.intercept_

5.144634379300555

In [45]:
model.coef_

array([0.00850098, 0.25228584])

In [46]:
y_act=y
y_pre=model.predict(X)

In [47]:
mean_squared_error(y_act,y_pre)

3.020107786882978

In [48]:
mean_absolute_error(y_act,y_pre)

1.4101981440023243

# Social Network

In [49]:
import pandas as pd

In [82]:
df=pd.read_csv('../../datasets/Social_Network_Ads.csv')
df

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [75]:
X=df[['Age','Purchased']]
y=df['EstimatedSalary']


In [76]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X,y)

LinearRegression()

In [77]:
model.coef_

array([ -372.45323554, 30792.53748762])

In [78]:
model.intercept_

72758.89443230575

In [79]:
y_act=y
y_pre=model.predict(X)

In [80]:
mean_absolute_error(y_act,y_pre)

25279.54599044125

In [81]:
mean_squared_error(y_act,y_pre)

998340749.8174039

# Salary Data Csv

In [83]:
import pandas as pd

In [87]:
df=pd.read_csv('../../datasets/Salary_Data_multi.csv')

In [88]:
df

YearsExperience   Age  Salary
0               1.1  21.0   39343
1               1.3  21.5   46205
2               1.5  21.7   37731
3               2.0  22.0   43525
4               2.2  22.2   39891
5               2.9  23.0   56642
6               3.0  23.0   60150
7               3.2  23.3   54445
8               3.2  23.3   64445
9               3.7  23.6   57189
10              3.9  23.9   63218
11              4.0  24.0   55794
12              4.0  24.0   56957
13              4.1  24.0   57081
14              4.5  25.0   61111
15              4.9  25.0   67938
16              5.1  26.0   66029
17              5.3  27.0   83088
18              5.9  28.0   81363
19              6.0  29.0   93940
20              6.8  30.0   91738
21              7.1  30.0   98273
22              7.9  31.0  101302
23              8.2  32.0  113812
24              8.7  33.0  109431
25              9.0  34.0  105582
26              9.5  35.0  116969
27              9.6  36.0  112635
28             10.3  37.0  122391
29             10.5  38.0  121872

In [89]:
X=df[['YearsExperience','Age']]
y=df['Salary']

In [90]:
from sklearn.linear_model  import LinearRegression
model=LinearRegression()
model.fit(X,y)

LinearRegression()

In [91]:
model.coef_

array([6153.35330145, 1836.01359426])

In [92]:
model.intercept_

-6661.98719881312

In [93]:
model.predict([[2,23]])

C:\Users\Hp\DSML39\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([47873.03207208])

In [94]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [95]:
y_act=y
y_pre=model.predict(X)

In [96]:
mean_absolute_error(y_act,y_pre)

4573.805204164708

In [97]:
mean_squared_error(y_act,y_pre)

29072857.848943133

# Salary Data Csv

In [98]:
import pandas as pd

In [100]:
df=pd.read_csv('../../datasets/Salary_Data_1.csv')
df

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [103]:
X=df[['YearsExperience']]
y=df['Salary']

In [104]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X,y)

LinearRegression()

In [105]:
model.coef_

array([9449.96232146])

In [106]:
model.intercept_

25792.20019866871

In [108]:
model.predict([[4]])

C:\Users\Hp\DSML39\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([63592.04948449])

In [109]:
from sklearn.metrics import mean_absolute_error,mean_squared_error


In [112]:
y_act=y
y_pre=model.predict(X)

In [114]:
mean_absolute_error(y_act,y_pre)

4644.2012894435375

In [115]:
mean_squared_error(y_act,y_pre)

31270951.722280968

# 3/7/2025

In [23]:
def isPrime(n):
    for i in range(2,n-1):
        return n%i!=0
        
            

In [24]:
isPrime(100)

False

In [13]:
isPrime(21)

True

# HealthInsurence

In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('../../datasets/Health_insurance.csv')
df

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [9]:
df['sex_enc']=df['sex'].map({'female':1,'male':0})
df['smoker_enc']=df['smoker'].map({'yes':1,'no':0})

In [10]:
df

age     sex     bmi  children smoker     region      charges  sex_enc  \
0      19  female  27.900         0    yes  southwest  16884.92400        1   
1      18    male  33.770         1     no  southeast   1725.55230        0   
2      28    male  33.000         3     no  southeast   4449.46200        0   
3      33    male  22.705         0     no  northwest  21984.47061        0   
4      32    male  28.880         0     no  northwest   3866.85520        0   
...   ...     ...     ...       ...    ...        ...          ...      ...   
1333   50    male  30.970         3     no  northwest  10600.54830        0   
1334   18  female  31.920         0     no  northeast   2205.98080        1   
1335   18  female  36.850         0     no  southeast   1629.83350        1   
1336   21  female  25.800         0     no  southwest   2007.94500        1   
1337   61  female  29.070         0    yes  northwest  29141.36030        1   

      smoker_enc  
0              1  
1              0  
2              0  
3              0  
4              0  
...          ...  
1333           0  
1334           0  
1335           0  
1336           0  
1337           1  

[1338 rows x 9 columns]

In [14]:
X=df[['age','sex_enc','bmi','children','smoker_enc']]
y=df['charges']

In [16]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X,y)


LinearRegression()

In [17]:
model.intercept_

np.float64(-12181.101839234441)

In [18]:
model.coef_

array([  257.73498767,   128.63985357,   322.36421449,   474.41112061,
       23823.39253065])

In [19]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [26]:
age=int(input('Enter your age:'))
gender=input('Enter gender(male/female):')
gender= 0 if gender=='male' else 1
bmi=float(input('Enter bmi'))
children=int(input('Enter no of childrens'))
smoker=input('Do you smoke(yes/no)')
smoker= 1 if smoker=='yes' else 0

X_test=[[age,gender,bmi,children,smoker]]
print(model.predict(X_test)[0])

Enter your age: 45
Enter gender(male/female): male
Enter bmi 12
Enter no of childrens 5
Do you smoke(yes/no) yes


29480.79131343054


C:\Users\Hp\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [30]:
# print(model.predict(X_test)[0])

In [31]:
y_act=y
y_pre=model.predict(X)

In [32]:
mean_absolute_error(y_act,y_pre)

4178.655987273669

In [33]:
mean_squared_error(y_act,y_pre)

36676355.79457731

In [34]:
import pickle

In [35]:
pickle.dump(model,open('model.pkl','wb'))